### ISSUE TITLE
Installer USB keeps rebooting

### ISSUE THREAD

**Issue by carstenmolewijk** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#1]
After everything I did, even replaced the SSD, the installer keeps rebooting. I need to mention, I created the installer on MacOS with a GUID Journal Ext format. I used the V3 EFI and did all the settings in AuxiliaryTools. Can you help me please? Did I forgot something in the bios? Try to install Monterey.
[config.plist.txt](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/files/11738645/config.plist.txt)

**Comment by carstenmolewijk** [comment]
The robot happens after the apple logo and the progress bar at apron 5%, the screen dimmed and reboots.

**Comment by 5T33Z0** [comment]
The BIOS Settings are listed in my Repo. You have to check those for yourself. 
Enable verbose output for some clues.

**Comment by 5T33Z0** [comment]
I will upload a new EFI tomorrow with fixed trackpad kexts.

**Comment by carstenmolewijk** [comment]
You have no idea what can cause the issue? Did you reset factory default first in the bios and the applied the settings? I am little bit a noob on this hackintoshing.

**Comment by 5T33Z0** [comment]
Which SSD (model) are you using? I hope you are not using `config.plist.text` to boot… 

## Instructions
- Download the [latest EFI](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/releases)
- Add boot-args for debugging: `-v` `debug=0x100` `keepsyms=1` to your config
- Add Serials and stuff to `PlatformInfo/Generic`
- Save the config.plist
- Mount the EFI partition of your USB installer (use MountEFI or OCAT)
- Place the EFI folder in it
- Reboot
- Enter BIOS
- Enable `Memory Card Slot`. Forgot to update the settings after finding kexts for it.
- Save the BIOS settings
- Reboot from USB flash drive (F12)

Good luck. If this doesn't work I suggest you follow the OpenCore Install guide to create your own config!

**Comment by 5T33Z0** [comment]
Set `SecureBootModel`to `Disabled` and try again. If it doesn't work I can't help you.

**Comment by Jan-E** [comment]
@carstenmolewijk Is the same EFI on the drive where you try to install macOS? Try to put it there after having formatted the drive. I sometimes got the impression that it used settings on that drive, even when you boot from a USB drive.

**Comment by 5T33Z0** [comment]
I've been rebooting from usb drive literally 100s of times last week to adjust the framebuffer patch. I am certain it does not do that!

**Comment by carstenmolewijk** [comment]
I go try all, I made a screenshot of the boot attached in this message. At this point it freezes.
![IMG_8117](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/16737933/a8ced59e-6597-4bbc-859a-819375aeacaf)

**Comment by carstenmolewijk** [comment]
> Set `SecureBootModel`to `Disabled` and try again. If it doesn't work I can't help you.

You mean in bios?

**Comment by carstenmolewijk** [comment]
> @carstenmolewijk Is the same EFI on the drive where you try to install macOS? Try to put it there after having formatted the drive. I sometimes got the impression that it used settings on that drive, even when you boot from a USB drive.

The drive is already empty :(

**Comment by 5T33Z0** [comment]
CONFIG.PLIST

**Comment by carstenmolewijk** [comment]
> CONFIG.PLIST

Disabled by default already, I give up :(

**Comment by 5T33Z0** [comment]
Try adding SMCLightSensor.kext that comes with virtual SMC

**Comment by 5T33Z0** [comment]
If your system doesn't use an Intel AC-9560 Wifi/BT card, use the official itlwm.kext.

**Comment by carstenmolewijk** [comment]
I literally give up now, don't know what's the issue 
[config.plist.txt](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/files/11792844/config.plist.txt)
![IMG_8120](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/16737933/18f9b978-d533-4246-b7f8-a9ce582b98b0)

Thanks for the help guys

**Comment by 5T33Z0** [comment]
Are you using this **.txt** file to boot?

**Comment by carstenmolewijk** [comment]
> Are you using this **.txt** file to boot?

Renamed to txt to upload in your GitHub. This config.plist on my usb. I created the USB on MacOS. GUID, macOS Journaled

**Comment by 5T33Z0** [comment]
Try other T490 EFIs. There are plenty available on github.

**Comment by carstenmolewijk** [comment]
I tried a lot last night, oh man i am so tired, every time it stops responding. Might it be hardware related?

**Comment by 5T33Z0** [comment]
1. Update to the latest BIOS
2. The errors have been reported on forums before. They are related to the ambient light sensor.  Mine doesn't have one in the hardware. That's why  `SSDT-ALS0` injects a fake Ambient Light sensor to keep macOS happy. You have to analyse your system's DSDT to check if your system has a real sensor and make it work with macOS: 

https://github.com/5T33Z0/OC-Little-Translated/tree/main/01_Adding_missing_Devices_and_enabling_Features/Ambient_Light_Sensor_(SSDT-ALS0)

Besides that I can't do nothing else for you.

**Comment by carstenmolewijk** [comment]
> 1. Update to the latest BIOS
> 2. The errors have been reported on forums before. They are related to the ambient light sensor.  Mine doesn't have one in the hardware. That's why  `SSDT-ALS0` injects a fake Ambient Light sensor to keep macOS happy. You have to analyse your system's DSDT to check if your system has a real sensor and make it work with macOS:
> 
> https://github.com/5T33Z0/OC-Little-Translated/tree/main/01_Adding_missing_Devices_and_enabling_Features/Ambient_Light_Sensor_(SSDT-ALS0)
> 
> Besides that I can't do nothing else for you.

Thank you so much for the info, I will check it out! I want thank you for the effort to help me!

**Comment by fldc** [comment]
For anyone revisiting this, the issue on my computer with the same problem was SSDT-PORTS, usbmap worked fine. :)
