### ISSUE TITLE
Screen error' after turn off

### ISSUE THREAD

**Issue by TUNBudi06** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#10]
IM having little trouble in display off modr,because the screen after off the color was change or having color issue.i mean artifact screen issues

So right now maybe IM using screen saver to prevent display off

My Spec
Efi: latest
T490 (20n3)
ram 16gb
Nvme midasforce 512gb custom nvme with sm2263xt

Can you fix it?

**Comment by 5T33Z0** [comment]
Try a framebuffer patch: https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/blob/main/Additional_Files/Framebuffer_Patches/UHD620_Framebuffer_Patches.plist

**Comment by TUNBudi06** [comment]
Just another report problem:
1.sometimes screen got darker even the brightness is full
2.sometime touchpad was kinda not responsif


That my problem so far

**Comment by 5T33Z0** [comment]
I don't have any issues like that. Try someone elses EFI if you are not satisfied with mine. Closing this issue since the original issue is resolved.
