### ISSUE TITLE
Memory information will not load

### ISSUE THREAD

**Issue by Krissh-C** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#12]
First of all, great work on the EFI. It works great but there is an issue regarding memory information. Specifications are the exact same as yours except for storage.

About this Mac will not open and neither will the about page in system settings. 

https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/117280851/9dad34ed-3b65-4dd5-b469-e9d6c93934af

Checking in System Information, it says "There was an error while gathering this information." Opening about this mac with System Information gives a report. ( https://pastebin.com/1VradYpy )

![Screenshot 2023-12-13 at 4 24 05 PM](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/117280851/9d2669d6-9c4f-492a-873d-99eb3bbfbf89)

Additionally, checking memory information in other apps (such as Onyx), have a blank space for memory type

![Screenshot 2023-12-13 at 4 31 22 PM](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/117280851/979edd6b-0bcd-46ea-97fe-c220c3a6a74d)

Using the EFI causes the issue as this issue is not present when using a different EFI such as the one I had made prior to using this. This happened on my old Ventura 13.6.3 install and also on my freshly installed Sonoma 14.2 install. All software and firmware updates have been installed.
BIOS Version: 1.81
EC Version: 1.27

**Comment by 5T33Z0** [comment]
I can't help you. As you can see, it's working without issues for me.

**Comment by 13ym-0777** [comment]
I have the same problem. My memory is 16GB of Magnesium, and the main board is also 16GB.

**Comment by 5T33Z0** [comment]
PlatformInfo >> Disable "Custom Memory" option!
