### ISSUE TITLE
Bluetooth cannot be turned on after adding the serial number. Bluetooth is normal before adding the serial number.

### ISSUE THREAD

**Issue by 13ym-0777** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#13]
Bluetooth is normal before adding the serial number. Bluetooth cannot be turned on after adding the serial number. My CPU is I7-8665U, which has this problem in Sonoma and Ventura.
![截屏2023-12-17 03 09 05](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/134766164/633a4404-d134-4061-bbf2-fc6a30dc42ce)

**Comment by 13ym-0777** [comment]
And there is an error in the memory, I can't open about this machine. After manually adding the memory information in OCC, about this machine can be opened normally, but OCC can't read the config, very strange...

**Comment by 5T33Z0** [comment]
- PlatformInfo: Disable "Custom Memory" option (I've enabled it on my system because RAM speeds were reported wrong so I had to add custom entries which I deleted before uploading the EFI folder)
- BT: only works for Intel AC-9560 (my card)
- ⚠️ Generate your own CPUFriendDataProvider kext if you use a different CPU!
- Don't use OpenCore Configuratort!

**Comment by 13ym-0777** [comment]
My bluetooth is also AC9560.

**Comment by 13ym-0777** [comment]
First of all, thank you very much for the EFI you made, it's really great, but I have tried to reinstall the system many times after the Bluetooth problem happened, but this Bluetooth problem still exists, mainly after I add the serial number. Once I add the serial number, the Bluetooth will not work. It is normal until I add the serial number.

**Comment by 5T33Z0** [comment]
Read the Instructions:

> `Platforminfo/Generic`: Generate an MLB, Serial and ROM for `MacBookPro15,2` with GenSMBIOS or OCAT. ⚠️ Don't change the SMBIOS or the USBMap.kext won't work anymore!

**Comment by 5T33Z0** [comment]
You don't need to repeat yourself.

**Comment by 13ym-0777** [comment]
Thanks, please forgive me for not reading your details, but which one is SMBIOS? Thank you very much for your answer.
![截屏2023-12-17 03 30 53](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/134766164/141515d9-0bb2-4694-b8ef-2d1deaadd756)

**Comment by 13ym-0777** [comment]
This is my first time trying black apple. Thank you very much for your generosity in sharing your efi, and thank you for your patience in answering my ignorant questions.

**Comment by 5T33Z0** [comment]
**USBMap_MBP152.kext**

- right-click
- "Show Package Contents"
- Open info.plist with propertry
- Change `model`to `MacBookPro16,3`

![Bildschirmfoto 2023-12-16 um 20 48 48](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/76865553/624edba5-a3d1-45bc-bfa8-fb1fa25e7c26)
