### ISSUE TITLE
iMessage and FaceTime not working in MacOS Sonoma

### ISSUE THREAD

**Issue by Unleqxt** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#14]
No problem here, I already got it working. In my experience, iMessage and FaceTime just don't work in macOS Sonoma with the Airportltwm kext but with the itlwm kext it just worked. When Airportltwm enabled, the two services would work when the thinkpad is connected via lan but when connected via wifi for example the messages in iMessage just wouldn't send. After like 2 minutes I got a notification: "Couldn't send Message".  I just want to tell others about the problem if they have the same issue and it would be nice if you could add in the comparison between the two kexts that iMessage and FaceTime won't work with Airportltwm.kext

Sorry my English isn't the best, it's not my native language.
I hope I can help somebody with this.
thanks

**Comment by 5T33Z0** [comment]
Thanks for the explanation. I did not know that iMessage does not work with airportitlwm causes. I will add the info to the pro/cons list
