### ISSUE TITLE
Battery drain faster than Windows

### ISSUE THREAD

**Issue by muhabaz** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#16]
thanks for share this config. all working fine in my machine that use i7-8665u and install sonoma. but i have a problem with battery drain. i test just open brave browser and browsing. 
in windows 1 hour reduce 10% but in macOS reduce 25-30%. i don't know why, but my fan got more extra work. and i think processor and disk too.
i try to set fan to lowest rpm. it will make processor temperature increase up to 70c. when i use windows, temperature  just up to 55c. maybe you have an experience this case and can help me about this.
thank you

**Comment by 5T33Z0** [comment]
I think YogaSMC is not handling CPU Power management optimally. But I think in general, Hackintoshes always do worse when running macOS vs running WIndows. But you could try the following:

- Disable YogaSMC kext (you will lose all Fn Shortcut Keys besides those for Volume and Brightness)
- DIsable YogaSMC preference pane from loading in System Settings (Login Items)
- Enable  CPUFriend and CPUFriendDataprovider kexts
- Enable SMCProcessor and SMCSuperIO kexts
- Save config and reboot

Monitor CPU behavior with Intel Power Gadget (compare CPU behavior when using YogaSMC vs. CPU Friend)

**Comment by muhabaz** [comment]
thanks for your advice. i followed that step, and still no change. i will try to disable config 1 by 1 to compare the differences
