### ISSUE TITLE
Installer is in German

### ISSUE THREAD

**Issue by jakerieger** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#17]
When I boot to the installer, everything is in German. I've tried changing the `prev-lang:kbd` settings in `config.plist` to `en-US:0` but this had no effect.

**Comment by 5T33Z0** [comment]
NVRAM Reset is your friend.

**Comment by jakerieger** [comment]
Followed the instructions here: https://elitemacx86.com/threads/how-to-reset-nvram-clover-opencore.939/

Doesn't seem to have any effect.

**Comment by 5T33Z0** [comment]
Don't change this key: `#prev-lang:kbd` 

Change this key: `prev-lang:kbd`

The first is a disabled placeholder, the 2nd is the actual key!

**Comment by jakerieger** [comment]
Fixed it, thanks! Sorry, coming from Clover. OpenCore is new to me.

**Comment by 5T33Z0** [comment]
If you see this `#` at the beginning of an entry, it's a disabled entry – no matter if it's in a Clover or OC config.plist!
