### ISSUE TITLE
USB-C ports won't work with USB 2.0 devices

### ISSUE THREAD

**Issue by prppedro** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#18]
Hello, ST33Z0

In first place, I'd like to thank you for all the effort in putting this package together. After some back and forth, I managed to successfully boot Mac OS Ventura. Yay! 

However, I have a very intriguing issue (and, judging by some search results on Google, I'm not alone): after plugging back my Dell WD15 dock, PD, display and network all worked great. Nice. But the not keyboard, nor the mouse. 

After fiddling a little more, I narrowed down the issue to the USB-C ports: it seems they simply won't recognize any USB 2.0 device, even if directly connected to them. USB 3.0 devices do work, though (like the dock's Ethernet MAU and a USB 3.0 thumb drive.) 

Seems like a mapping issue... Should I try to remap? I see people recommending [that tool](https://github.com/USBToolBox/tool). But since you advised that changing those configs. may break NVRAM and product spec., I'd like to ask you on what would be the best course of action. 

Thanks! 
-trp

**Comment by 5T33Z0** [comment]
My ports are mapped via ACPI.

So you either have to edit the Ports.aml file or use the usbport.kext located in my repo in the additional diles section.

Make sure to disable the usb port ACPI table (ACPI/Add) and the drop rule (under ACPI/delete) when using the kext.

02.03.2024 09:10:45 Pedro T. R. Pinheiro ***@***.***>:

**Comment by prppedro** [comment]
Hey, thanks for the prompt response! 

It seems to me that editing the AML looks like the most fool-proof approach (this is my very first Hackintosh, mind you). The problem is: how do I know what are the missing ports and their addresses? 

-trp

**Comment by 5T33Z0** [comment]
If you are unfamiliar with mapping usb ports and editing ACPI tables, I suggest you use the kext method  instead. Because my acpi table affects all OSes.

02.03.2024 10:28:23 Pedro T. R. Pinheiro ***@***.***>:

**Comment by 5T33Z0** [comment]
Helpful Resources: https://github.com/5T33Z0/OC-Little-Translated/tree/main/03_USB_Fixes

**Comment by prppedro** [comment]
Alright... I'll try that later this day and report back. I once again thank you for your prompt support. 

-trp

**Comment by prppedro** [comment]
Generating `Kext` with USBToolBox solved the issue. Thanks for the support! 

![Screenshot 2024-03-03 at 14 26 39](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/9347060/8f7da9d6-c973-44cf-a122-718c74ab1b23)

**Comment by prppedro** [comment]
The only thing not working now is the WD15 Realtek audio. But this might be not Hackintosh realated.

**Comment by 5T33Z0** [comment]
The audio issue is related to usb for some odd reason. You can try my USB kext: https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/blob/main/Additional_Files/USB/USBMap.kext.zip
