### ISSUE TITLE
Can't not connect to any bluetooth mouse

### ISSUE THREAD

**Issue by Ngdaz** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#19]
![Screenshot 2024-03-04 at 11 44 30](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/47729815/4a61f3bd-a4bd-47f6-b5e2-f7b77adf578e)

I can't connect with any Bluetooth mouse device, I've anywhere 3, and SteelSeries rival 3. Only works with a USB dongle. And also for the keyboard, I can't use both Bluetooth and dongle mode so I need to use wire mode.

**Comment by Ngdaz** [comment]
The mouse shows up in the list of nearby devices but after 30 seconds of loading, it looks like connected for 1s and then disconnected.

**Comment by Ngdaz** [comment]
Update: Can work with Bluetooth 5.0 on my  NJ80 keyboard because it separates the BT5.0kb and BT3.0kb connection so when I choose the 5.0 one it works. Will try with some more device if I can

**Comment by 5T33Z0** [comment]
The Intel-AC 9560 supports BT 5.1 . Don't know about the downward capabilities. But Sharing files from my phone via BT works fine.
