### ISSUE TITLE
Location services through Wifi

### ISSUE THREAD

**Issue by Jan-E** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#2]
https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/blob/122bbf3e3a7ef6ee7adfd29641e9c443cf152115/README.md?plain=1#L165

Pro for AirportItlwm.kext: it supports Location Services.

>Does it support Location Services
>Supported on AirportItlwm.kext.
>
>itlwm.kext reports the Wi-Fi card as an Ethernet NIC to macOS, rather than Wi-Fi. This means that Find My does not work, since it relies on Wi-Fi data (like what networks are around you). This likely means that other location services don't work as well.

Quote from https://openintelwireless.github.io/itlwm/FAQ.html#features

**Comment by 5T33Z0** [comment]
**Pro** Itlwm: Supports connecting to Hidden Wi-Fi networks

So what's the point of your issue report? 

I don't use Find my Mac nor Location Services – they are irrelavant to me. 

Am I obligated to list _ALL_ pros and cons on my repo now? Or is it okay, to list those that are relevant to _me_?

**Comment by Jan-E** [comment]
>I don't use Find my Mac nor Location Services – they are irrelavant to me.

They may be relevant for people that use your repo as template. IMHO it is quite a difference and the reason why I chose for AirportItlwm.kext on some hackintoshes. But of course that is up to you. Your repo, your choice.
