### ISSUE TITLE
My t490 can't upgrade to  macOS 14.4

### ISSUE THREAD

**Issue by jack338c** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#21]
Hello
I just create a USB Installer with OCLP to install macOS 14.4 on a new APFS
but it will always reboot after enter Macos install (the white icon)
(already click the macOS Sonoma installer (the color icon)  and finished installing

Do you have any idea to fix this
My t490 has win /mac/linux 3 OS
![Screenshot 2024-03-10 at 6 23 44 PM](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/10782586/cd20cf1b-7707-414d-b0a9-830f2f581a38)

thanks

**Comment by 5T33Z0** [comment]
Set `Misc/Security/SecureBootModel` to `Disabled`. You can re-enable it after installation is finished

**Comment by jack338c** [comment]
thank you very much for your help !

**Comment by fldc** [comment]
@5T33Z0 Did you try the solution to upgrade after disabling securebootmodel and airportitlwm? Do you know if it works here too?

**Comment by 5T33Z0** [comment]
@fldc I can't recall. Just try it and report back

**Comment by fldc** [comment]
> @fldc I can't recall. Just try it and report back

Ok, tried it, switch to itlwm, disable securebootmodel, reset nvram and update, everything is fine.

**Comment by 5T33Z0** [comment]
Thanks. I think I have only tried disabling one or the other, not both. I will update the instructions in the repo
