### ISSUE TITLE
Thunderbolt not working 

### ISSUE THREAD

**Issue by Ngdaz** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#22]
Hi, I've tested thunderbolt 3 with my M27Q monitor and I can't make my T490 to export display through USB C port in the monitor (using supported type C cable, Baseus-20GB-240W-cable). In setting I can see my monitor show up with correct name, I can change the Refresh rate, Color profile and resolution, event I can change arrangement of each monitor. But still get black screen and the monitor reported: no signal from type C port. Is there any way to fix it? :(((((((

p/s: not work with ugreen type c to HDMI hub too, but show up correct monitor in the setting

**Comment by 5T33Z0** [comment]
I don't have a USB Type-C Hub, so I can't test this. Try to disable ports.aml and the ACPI/delete rule for dropping the original port mapping and enable the USB.ports kext instead. If this doesn't help you have to generate your own USB ports kext

**Comment by Ngdaz** [comment]
Thank you I will try

**Comment by Ngdaz** [comment]
Hey @5T33Z0, I found it. The power type c port works LoL. I can export display through it and now  the Thunderbolt port works as power for my laptop :v

**Comment by Ngdaz** [comment]
New update, now I switch back to the correct port and it works. So weird lol

**Comment by 5T33Z0** [comment]
Ok. Did you change anything to make it work?

**Comment by Ngdaz** [comment]
Just switch to use USB.ports kext and after some test it works

**Comment by Ngdaz** [comment]
I've tried to use SSDT Thunderbolt from this repo but now I have removed it and use only your EFI, it's till works https://github.com/tylernguyen/x1c6-hackintosh

**Comment by Ngdaz** [comment]
So my solution is to plug the Thunderbolt device in the power and the power into the Thunderbolt port, then switch back. Now both HDMI and Thunderbolt ports work for me to use 2 monitors also with Clamshell mode

**Comment by Ngdaz** [comment]
![image](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/47729815/9c40810d-f31c-4453-9d1b-a439bf2089b6)
