### ISSUE TITLE
Install OSX on WWAN SSD?

### ISSUE THREAD

**Issue by LiwiuszPleandro** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#23]
Is it possible to install, boot and work MacOSX on the second drive SSD (WD sn520 ssd nvme m.2 2230 - visible and work in Windows11) in the WWAN port when the first default nvme drive m2 contains Windows11 encrypted with Bitlocker (TPM)?

**Comment by Jan-E** [comment]
I did that with the T530 EFI on a X230t. If you boot from the M.2 SSD there even is a chance that OpenCore recognizes that Windows is installed on the other SSD and offers dual boot. Otherwise you will have to choose the boot SSD at machine start-up.

**Comment by LiwiuszPleandro** [comment]
@Jan-E: ThinkPad T490. I have a Windows system installed on the first disk, not the second. I am asking for suggestions: What is the order to keep the OS X installation and how to carry it out so as not to damage the encrypted Windows?
- first disk NVME M2 Crucial 2280 1TB Windows11 TPM crypted Bitlocker  (C: D: E:)
- second disk WWAN WD SN520 SSD NVME M2 2230 (for OSX)
How do you think Do I have to decipher all partitions?

**Comment by 5T33Z0** [comment]
Bitlocker is a per disk feature so it doesn't really matter for the 2nd disk. But in order to boot macOS, you need to disable Secure Boot, which might interfere with Bitlocker (warning symbol on the disk icon).

You probably should put the OpenCore EFI on the 2nd disk and make boot from that.

Also, if you format the 2nd disk for macOS it won't be accessible from Windows 11 any more, since WIndows does not support APFS.

**Comment by JuiZZZe** [comment]
as I know issue with second ssd for t490 it was not possible to install at all from the beginning, later even after installation it is not bootable 
🤔

**Comment by LiwiuszPleandro** [comment]
It seems to me that the problem lies in the fact that not all drives in the WWAN port are visible in the UEFI in the T490. Presumably Lenovo may have a black list of unsupported devices. I haven't installed OSX on the drive in the WWAN port yet, but I have used the drive in the port and it was visible under Windows 11 (WWAN: WD SN520 SSD NVME M2 2230). I haven't installed a system on it yet, so I don't know if it will be bootable. I am still interested in installing OSX on this drive, hence I am looking for confirmation if it is possible.

Following the article https://github.com/perez987/OpenCore-and-UEFI-Secure-Boot you can see that it is possible to generate a certificate for the OSX bootloader in conjunction with the Bitlocker Windows11 partitions I have with me, but it is a tedious process, hard and problematic, but possible.
