### ISSUE TITLE
DYTC wont works

### ISSUE THREAD

**Issue by m1k0lay** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#24]
![Снимок экрана 2024-04-12 в 09 03 26](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/39671588/dcc80de5-e2ac-47a1-9c72-377fab4182c7)
Switcher isn't active, can't switch DYTC mode.

**Comment by 5T33Z0** [comment]
I"ve noticed that irt becomea unavailable after some time. No idea, why.

In my experience, it's best to leave it at standard. Or disable yogasmc completely and use cpufriend and the dataprovider kext instead
