### ISSUE TITLE
Fail to open YogaSMCPane

### ISSUE THREAD

**Issue by m1k0lay** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#25]
![Снимок экрана 2024-04-12 в 09 07 35](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/assets/39671588/c07cb3ef-a2c6-4afe-9ab8-d252ffca12fe)
When i press hotkeys (fn+f9) or try open YogaSMCPane from context menu YogaSMCNC i get this message

**Comment by 5T33Z0** [comment]
Do it twice. Or install the alternatw version libked on my repo.
