### ISSUE TITLE
Samsung PM961 NVMe

### ISSUE THREAD

**Issue by tonyrh** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#26]
Sorry for opening an issue just to ask a question, but I'm really stuck and can't find any definitive info about my issue.
Basically everything goes fine with the installation on my T490 with a Samsung PM961 NVMe (reported as MZVLW512HMJP-000H7 in Disk Utility) up until after the first reboot. I get the Apple logo with ~25 minutes remaining, it goes on for a while up to ~15 minutes remaining, then it reboots and goes into a reboot loop. 
Could this be caused by this particular Samsung NVMe?

**Comment by tonyrh** [comment]
Thanks for the info! 
It looks like the PM961 is the OEM version of the 960 EVO (same controller Polaris S4LP077X01-8030, same NAND flash, same speeds etc).
The guide does not mention the 960 EVO either, but it could be the culprit.
It could also be something else entirely as this is my first attempt at using OpenCore though: I don't know if there is a way to access any logs, do you have any suggestions to diagnose my situation? Is a reboot loop in the later stage of macOS installation a common/known issue in your experience?

**Comment by tonyrh** [comment]
To disable AitportItlwm.kext is enough to set Enabled to False in the various dictionaries containing AirportItlwm_14.4.kext, AirportItlwm_Sonoma.kext etc or do I have to remove the .kext files/directories from EFI/OC/Kexts ?

**Comment by 5T33Z0** [comment]
Read the instructions in the repo. That's what I wrote them for.

**Comment by tonyrh** [comment]
Do you mean the changelog that says:

> Updating from 14.3.1 to 14.4 via System Update crashes the installer early.
 
or the caution note:

> Upgrading from to macOS 14.3.1 to 14.4 via System Update causes a Kernel Panic during install! 

I'm doing a fresh installation on an empty disk...

Anyway, on the Dortania guide that you link I see that:

> The config.plist must match the contents of the EFI folder. If you delete a file but leave it listed in the Config.plist, OpenCore will error and stop booting.

but it's talking about the other way around, leaving kexts enabled but deleting the files.
I think if kernel extensions in macOS work like kernel modules in Linux, leaving the files intact but telling the kernel to avoid loading them should be fine?

**Comment by 5T33Z0** [comment]
Kexts can be enabled/disabled in the config. Don't delete files.

- Disable `AiportItlwm` kexts and enable `itlwm.kext` insteaed. 
- Set `SecureBootModel` to `Disabled`
- Install macOS

If this doesn't work it's most likely an SSD issue.
