### ISSUE TITLE
Picker not detecting offline installer partition

### ISSUE THREAD

**Issue by rastiqdev** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#3]
Hi,

I've tried installing your EFI on my laptop with the Olarila image of macOS Ventura 13.5 but when I got to the OpenCore picker screen, the "Install macOS Ventura" partition was not visible. 
I've tried setting `HideAuxiliary` to `true`, `ThirdPartyDrives` to `true`, but nothing changed.

Any help would be appreciated.

**Comment by 5T33Z0** [comment]
NO Support for Olarilla Stuff!
