### ISSUE TITLE
Reset upon booting

### ISSUE THREAD

**Issue by nikitajeganpp** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#31]
I am trying to set up Sonoma with your EFI on a T490s.

I have successfully turned three Nuc10s into Hackintoshs in the past. Now, I also wanted to build a Hackintosh Laptop.

I have created a bootable USB-Drive on windows and on mac.
I have inserted your EFI into the USB-Drive.
The EFI is in the default condition as downloaded.
The Bios has been set as you have instructed.
The T490s recognizes the drive and boots from it.
But after about a seventh of the Apple progress bar, the laptop resets and boots again.

Any advice on that is highly appreciated.

**Comment by 5T33Z0** [comment]
Okay. Try the latest release: https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/releases/tag/OC_101.5
 
I've used it to install macOS Sonoma and Sequoia on a new NVME this weekend and it worked flawlessly.

Did you read my note about the NVME that comes with the Laptop, the Samsung PM981a NVMe? It's incompatible with macOS.

**Comment by nikitajeganpp** [comment]
Thanks. I have read about the NVME and had already exchanged it for a new Crucial drive.

I will try your new version tonight or during the next days and will let you know.

**Comment by salmonzik01** [comment]
Any news? I'm having the exact same problem.

**Comment by nikitajeganpp** [comment]
Sorry, it took me a while to try it out. I have tested your newest release but the issue is still there.
