### ISSUE TITLE
Can't use Photo Booth app with Lenovo.T490.OpenCore.1.0.1.v4.0

### ISSUE THREAD

**Issue by jack338c** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#32]
Hello Master
Can't open Photo Booth app ,Could you help me check it out
thanks
![Screenshot 2024-07-29 at 1 16 36 PM](https://github.com/user-attachments/assets/2786a4ea-320a-4226-a38d-13c27c76455f)

**Comment by 5T33Z0** [comment]
Thanks for the info. I forgot to enable the camera in BIOS before I remapped USB in June, so Port `HS08` which is required for the cam was not part of port mapping.

Repplace the USBMap.kext with the one linked below and it should work again:

[USBMap.kext.zip](https://github.com/user-attachments/files/16408439/USBMap.kext.zip)

**Comment by jack338c** [comment]
it's working now !
many thanks for your help 🥂
