### ISSUE TITLE
itlwm is not running

### ISSUE THREAD

**Issue by jsiemonski** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#33]
Tried the new release, but Heliport keeps reporting itlwm is not running, and wifi doesn't work. I am still on 14.5, possibly why?

**Comment by 5T33Z0** [comment]
As stated in the OC Changelog:

> Changed Wifi kext loading:
>
>  - macOS Sonoma uses AirportItlwm_Sonoma
> -  macOS Sequoia uses itlwm.kext. Connect to Wi-FI via Heliport App!

So, in other words:

1. itlwm is not loaded in Sonoma
2.SInce itlwm is not loaded in Sonoma, Heliport does not work
3. Since AirportItlwm is use in Sonoma you don't need Heliport to connect to wifi.

**Comment by jsiemonski** [comment]
Gotcha - so if I upgrade to this version, I can't use itlwm, so iMessage doesn't work via wifi, correct?

**Comment by 5T33Z0** [comment]
I don't use Messages, so you have to figure this out on your own. If you want to use itlwm in Sonoma , just disable the Airportitlwm kext and change `MinKernel` for itlwm.kext to `23.0.0`

**Comment by jsiemonski** [comment]
Will try that, I didn't change the MinKernel version. Thank you!

**Comment by jsiemonski** [comment]
I wasn't saying you said I changed it, I meant I didn't change that value when I had it enabled. It worked once I downgraded it to 23.0.0. Thanks!
