### ISSUE TITLE
"0251 cmos checksum bad" after wakeup from hibernation 

### ISSUE THREAD

**Issue by nikolayperin** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#35]
Have "0251 cmos checksum bad" message after wakeup on hibernatemode 25. On hibernatemode 3 don't have this message.

**Comment by nikolayperin** [comment]
Possible solution: [HibernationFixup](https://github.com/acidanthera/HibernationFixup) + [RTCMemoryFixup](https://github.com/acidanthera/RTCMemoryFixup) + boot-args: rtcfx_exclude=80-AB + [ReservedMemory dict in config.plist](https://github.com/acidanthera/OpenCorePkg/commit/76bf9bdead9c73db1651d54ac5532bb49fcebe59)

- https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/issues/103
- https://github.com/tylernguyen/x1c6-hackintosh/issues/44#issuecomment-697270496

**Comment by 5T33Z0** [comment]
Thanks for the info. I've implemented your suggestions. test the updated EFI: https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/releases/tag/OC_102.2

Let me know if it works.

**Comment by nikolayperin** [comment]
Reboot after ware up, and check disk errors
![Снимок экрана 2024-09-29 в 20 10 26](https://github.com/user-attachments/assets/80cadeee-71be-4ecd-81b3-f3077531ce22)

**Comment by 5T33Z0** [comment]
I guess then you have to stick to hibernatemode 3 or try to resolve the issues yourself, since I don't have the time to investigate this.

**Comment by 5T33Z0** [comment]
Do you have the latest firmware for the 970 Evo plus installed? This ssd is known to be problematic for hackintoshing…

**Comment by nikolayperin** [comment]
<img width="650" alt="Снимок экрана 2024-10-22 в 00 27 48" src="https://github.com/user-attachments/assets/5aaf9510-15e8-4ac5-b04f-f2f52e8aebd2">
Last version. If trust samsung magician...

**Comment by 5T33Z0** [comment]
I can't verify your issue so I am closing this.
