### ISSUE TITLE
Question: Is there a MacOS native BlueTooth WiFI Card that can be installed?

### ISSUE THREAD

**Issue by cyberfunk** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#38]
I have a Lenovo Yoga Thinkpad 260 running a native MacoS compatible Wifi Bluetooth card. I have all of the features of a genuine Macbook including airdrop, find my mac, facetime, imessage etc. Is there any card that is native to MacOS that can be installed to the T490?

**Comment by jsiemonski** [comment]
@cyberfunk curious about your Yoga.. what card are you using? Internal or external? The T490 works pretty well with Heliport and itwlm. Airdrop and find my mac don't work, but FT, iMessage, and Find My Friends work great. I haven't tried anything BT yet. Unfortunately the wifi card is soldered in the T490. I considered trying some USB to PCIe to AirCard stuff, but haven't.

**Comment by cyberfunk** [comment]
I closed my questiopn because the bluetooth wifi card is soldered on in the T490 correct? If so there is no way to replace it internally. For my Yoga 260 I'm using the Broadcom BCM94360CS2 with a kick a$$ adapter. This Thinkpad Yoga 260 works better than a macbook because you can enable touch screen which no macbook has. EVERYTHING else works as good or better than a MacBook! The only reason I'm looking at upgrading to the T490 is I've reached legitimate end of the road with Skylake graphics and MOnterey. Starting with Ventura I see only issues. I tried spoofing kaby lake to move to Ventura but it was super buggy and unstable which is a no go for me. I need rock solid whic MOnterey is on htis beast. Anyway thanks for posting your solution and I will probably be using your build once I buy a T490.

**Comment by jsiemonski** [comment]
Nice! I bought mine refurbished on Amazon for under $300 and replaced the M.2 with a 2TB drive. That’s correct, and Lenovo likes to police what hardware is used anyway. I have an M93p that I tried replacing the adapter in, and it refused to boot. I am running Sequoia on my T490 and am super satisfied.

**Comment by cyberfunk** [comment]
Cool man! Glad to hear it. I got this Yoga 260 for FREE!!! I was leaving LA to do some world traveling and a guy from a movie studio was getting rid of a stack of old laptops for free. I grabbed all of them, sold every one but this Yoga which was in perfect condition. I hacked it with OpenCore and this baby has been solid as a rock going on just over 2 years now. I don't even use an internal battery anymore because those always swell up anyway and you can just run it off the AC adapter. It's feather weight without the battery. It's a bit underpowered for video editing but with patience I can get everything done from DJ to PhotoShop to Final Cut pro! Truly a blessing and a lucky find. All the best to you and thanks again for sharing your work here on GitHub!

**Comment by jsiemonski** [comment]
Very cool! Not my work, but 5T33Z0 is awesome :)
