### ISSUE TITLE
Not working: Micro SD Card reader

### ISSUE THREAD

**Issue by tjjjia** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#39]
Great work on this, thank you so much!

In macOS Sonoma, I cannot use the built-in card reader. Any instructions on how to proceed?
I have a dual boot system running, I can confirm the card reader works on Windows 11.

**Comment by 5T33Z0** [comment]
Works for me: 

![Bildschirmfoto 2024-10-22 um 16 36 49](https://github.com/user-attachments/assets/8e0059bb-6332-4476-9e46-7f7778c3e7fd)

**Comment by 5T33Z0** [comment]
I've noticed that the card has to be inserted before booting into macOS. Otherwise it it won't be detected.

This is probably a compatibility issues - because the kext hasn't been updated by the dev since Ventura.

**Comment by CrappyGamingXD** [comment]
In Sonoma when I try to use the microSD slot my computer freezes and I have to force shutdown and restart. Is this the same behavior you are experiencing?

**Comment by tjjjia** [comment]
> I've noticed that the card has to be inserted before booting into macOS. Otherwise it it won't be detected.
> 
> This is probably a compatibility issues - because the kext hasn't been updated by the dev since Ventura.

Gotcha, thanks for the context. I will try it next time (probably not until next week) and report back!

> In Sonoma when I try to use the microSD slot my computer freezes and I have to force shutdown and restart. Is this the same behavior you are experiencing?

No, fortunately not like that. Nothing happens at all.

**Comment by tjjjia** [comment]
> I've noticed that the card has to be inserted before booting into macOS. Otherwise it it won't be detected.
> 
> This is probably a compatibility issues - because the kext hasn't been updated by the dev since Ventura.

Tried this, does not work.

I might downgrade to Ventura,

**Comment by 5T33Z0** [comment]
No need to downgrade. Just create a new APFS volume and a bootable USB installer (you can use OpenCore Legacy Patcher to do so) and then you can install it on the newly created APFS volume.

**Comment by tjjjia** [comment]
Great tip @5T33Z0! Thank you!
