### ISSUE TITLE
Hibernation not working

### ISSUE THREAD

**Issue by mars704** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#40]
My laptop configuration is similar to yours, except that the CPU model is Intel i7-8565u and the RAM is 12G (8G+4G), I configured the BIOS and installed MacOS (Sonoma) according to your docs, generated the CPUFriendDataProvider.kext file and enabled the hibernation configuration, but the hibernation function does not work. I can't get back to the system properly after hibernation, I don't know what else could be the problem, could it be a memory problem?

**Comment by mars704** [comment]
panic(cpu 0 caller 0xffffff8019f946de): Sleep transition timed out after 180 seconds while entering darkwake on way to sleep. Suspected bundle: com.apple.iokit.IOGraphicsFamily. Thread 0x79.
Failure code:: 0x79f2f7e4 00000031

Backtracing specified thread
Panicked task 0xffffff8b82a0ddd8: 211 threads: pid 0: kernel_task
Backtrace (CPU 0), panicked thread: 0xffffff8b81b70b30, Frame : Return Address
0xffffffac82c2f790 : 0xffffff8019975817 
0xffffffac83117970 : 0xffffff8019854976 
0xffffffac83117a00 : 0xffffff8019852a70 
0xffffffac83117a50 : 0xffffff8019972740 
0xffffffac83117a90 : 0xffffff8019971f2b 
0xffffffac83117ad0 : 0xffffff7faea42fd5 
0xffffffac83117b00 : 0xffffff7faea5cf29 
0xffffffac83117b10 : 0xffffff7faea461b0 
0xffffffac83117ba0 : 0xffffff7faea4bd6c 
0xffffffac83117c40 : 0xffffff8019edca26 
0xffffffac83117cb0 : 0xffffff8019ef9dc5 
0xffffffac83117d50 : 0xffffff8019edd249 
0xffffffac83117da0 : 0xffffff8019ef6d35 
0xffffffac83117e40 : 0xffffff8019ef3015 
0xffffffac83117e90 : 0xffffff8019ef0b12 
0xffffffac83117ee0 : 0xffffff8019ef09ab 
0xffffffac83117f20 : 0xffffff8019f0f1de 
0xffffffac83117f60 : 0xffffff8019f0e806 
0xffffffac83117fa0 : 0xffffff80197c019e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOGraphicsFamily(598.0)[79F2F7E4-E451-35E1-BF22-1EFFA4192888]@0xffffff7faea39000->0xffffff7faea67fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[EF2F60F1-E128-37D6-9890-1116DC5A34D8]@0xffffff801bb69000->0xffffff801bb9afff

Process name corresponding to current thread (0xffffff8b81b70b30): kernel_task
Boot args: gfxrst=1 rtcfx_exclude=80-AB

Mac OS version:
23H124

Kernel version:
Darwin Kernel Version 23.6.0: Wed Jul 31 20:48:44 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_X86_64
Kernel UUID: 67760982-25DC-34FC-A09E-E5624B8B4D62
roots installed: 0
KernelCache slide: 0x0000000019400000
KernelCache base:  0xffffff8019600000
Kernel slide:      0x00000000194e4000
Kernel text base:  0xffffff80196e4000
__HIB  text base: 0xffffff8019500000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 1

System uptime in nanoseconds: 2401726564406
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000022f320f0c31
  Sleep   : 0x000001e2ca5c708f 0x00000009c4cc34c0 0x0000000000000000
  Wake    : 0x000001e2e44ee395 0x000000066c9a56ec 0x000001e2cf9ecacd
Compressor Info: 1% of compressed pages limit (OK) and 1% of segments limit (OK) with 1 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff804e7b5000 - 0xffffffa04e7b5000
  . PGZ   : 0xffffff804e7b5000 - 0xffffff804ffb6000
  . VM    : 0xffffff804ffb6000 - 0xffffff851c8e9000
  . RO    : 0xffffff851c8e9000 - 0xffffff86b614f000
  . GEN0  : 0xffffff86b614f000 - 0xffffff8b82a82000
  . GEN1  : 0xffffff8b82a82000 - 0xffffff904f3b5000
  . GEN2  : 0xffffff904f3b5000 - 0xffffff951bce8000
  . GEN3  : 0xffffff951bce8000 - 0xffffff99e861b000
  . DATA  : 0xffffff99e861b000 - 0xffffffa04e7b5000
  Metadata: 0xffffff802c3a5000 - 0xffffff804c3a5000
  Bitmaps : 0xffffff804c3a5000 - 0xffffff804e7a5000
  Extra   : 0 - 0

**Comment by 5T33Z0** [comment]
It seems that the system was trying to handle a dark wake event while it was in the process of going to hibernate, and something got stuck in the graphics subsystem (IOGraphicsFamily). The system waited for 180 seconds for this transition to complete before giving up and panic'ing.

I don't know how to fix this since I cannot re-create it. My suggetstion is to change hibernatemode to 0 and just use regular sleep.
