### ISSUE TITLE
HDMI connector issue

### ISSUE THREAD

**Issue by nikolayperin** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#42]
When external display connected to HDMI and lid closed if notebook goes to sleep, disconnect HDMI and open lid screen is black and keyboard backlight is off. But i don't use SSDT-EXT4-WakeScreen.aml... This is it?
![Снимок экрана 2024-12-01 в 02 26 47](https://github.com/user-attachments/assets/875677e7-6ed0-4ae0-a004-e5f969ed1134)
[mac-t490.ioreg.zip](https://github.com/user-attachments/files/17967303/mac-t490.ioreg.zip)

**Comment by 5T33Z0** [comment]
You need to open the lid _BEFORE_ disconnecting the external display
