### ISSUE TITLE
Cant boot Ventura latest

### ISSUE THREAD

**Issue by TUNBudi06** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#7]
IM using method by flashing throught USB and replacing Efi partition using this method

But stuck in moment and cant boot?
Theres no log to provide

**Comment by TUNBudi06** [comment]
My device was
T490 20n2
Using ssd skhynix_hfs256GD9TNG-l5b0b


And now IM facing kernel nvme kernel panic issue

Please help

**Comment by 5T33Z0** [comment]
I've upgraded to macOS Sonoma an it's working fine. Check your NVME for compatibility issues with macOS.

I can't hel you without any logs.
