### ISSUE TITLE
Black screen (backlight on) on wake from sleep. (Ventura 13.6)

### ISSUE THREAD

**Issue by fd1k** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#8]
Hello everyone, 
So far, everything is working, I have only changed some small things for iServices which are also working.
I have noticed one issue, and that is whenever I wake my laptop from sleep, the backlight is on, but the screen stays black. I have tried some steps to fix this, and so far none of them work. What should I check or change?
Thanks.

**Comment by 5T33Z0** [comment]
Hi. You could try different Framebufferpatches: https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/blob/main/Additional_Files/Framebuffer_Patches/UHD620_Framebuffer_Patches.plist

**Comment by fd1k** [comment]
Fixed, sleep works fine. Changed framebuffer patch.
