### ISSUE TITLE
Post-install T490 not detecting NVME EFI

### ISSUE THREAD

**Issue by 4paulpak** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#9]
Hi,
After install everything works. When I try to move my EFI from the USB to the built in NVME it is not detected by the BIOS. I only see the option to start Windows Boot Menu (no Windows on the drive) and Network. Any hints?
Thanks

**Comment by 5T33Z0** [comment]
- NVRAM Reset
- Check Boot entries order in BIOS (F12)

**Comment by TUNBudi06** [comment]
Try creating Efi partition with Windows installer or you can using offline installer

Sometime you cant detect the Efi partition if not set correctly

**Comment by 4paulpak** [comment]
thanks for all your help and suggestions. I have updated the BIOS and am using a different NVMe now and it works fine
